drop database BBD
create database BBD
:r C:\Users\bbdnet2897\Desktop\BBD_DATABASE\CreateTable\BBDFundTable.sql
:r C:\Users\bbdnet2897\Desktop\BBD_DATABASE\CreateTable\ContactDetail.sql
:r C:\Users\bbdnet2897\Desktop\BBD_DATABASE\CreateTable\DocumentTable.sql
:r C:\Users\bbdnet2897\Desktop\BBD_DATABASE\CreateTable\ProvinceTable.sql
:r C:\Users\bbdnet2897\Desktop\BBD_DATABASE\CreateTable\RaceTable.sql
:r C:\Users\bbdnet2897\Desktop\BBD_DATABASE\CreateTable\RoleTable.sql
:r C:\Users\bbdnet2897\Desktop\BBD_DATABASE\CreateTable\StatusTable.sql
:r C:\Users\bbdnet2897\Desktop\BBD_DATABASE\CreateTable\StudentApplicationTable.sql
:r C:\Users\bbdnet2897\Desktop\BBD_DATABASE\CreateTable\StudentInformationStudentApplicationTable.sql
:r C:\Users\bbdnet2897\Desktop\BBD_DATABASE\CreateTable\StudentInformationTable.sql
:r C:\Users\bbdnet2897\Desktop\BBD_DATABASE\CreateTable\UniversityFundApplication.sql
:r C:\Users\bbdnet2897\Desktop\BBD_DATABASE\CreateTable\UniversityStudentInformationTable.sql
:r C:\Users\bbdnet2897\Desktop\BBD_DATABASE\CreateTable\UniversityTable.sql
:r C:\Users\bbdnet2897\Desktop\BBD_DATABASE\CreateTable\UniversityUser.sql
:r C:\Users\bbdnet2897\Desktop\BBD_DATABASE\CreateTable\UserRoleTable.sql
:r C:\Users\bbdnet2897\Desktop\BBD_DATABASE\CreateTable\UsersTable.sql
:r C:\Users\bbdnet2897\Desktop\BBD_DATABASE\Constraint\DocumentConstraint.sql
:r C:\Users\bbdnet2897\Desktop\BBD_DATABASE\Constraint\StudentApplicationConstraint.sql
:r C:\Users\bbdnet2897\Desktop\BBD_DATABASE\Constraint\StudentInformationConstraint.sql
:r C:\Users\bbdnet2897\Desktop\BBD_DATABASE\Constraint\StudentInfoStudentApplicationConstraint.sql
:r C:\Users\bbdnet2897\Desktop\BBD_DATABASE\Constraint\UniversityConstraint.sql
:r C:\Users\bbdnet2897\Desktop\BBD_DATABASE\Constraint\UniversityFundApplicationContraint.sql
:r C:\Users\bbdnet2897\Desktop\BBD_DATABASE\Constraint\UniversityStudentConstraint.sql
:r C:\Users\bbdnet2897\Desktop\BBD_DATABASE\Constraint\UserRoleConstraint.sql
:r C:\Users\bbdnet2897\Desktop\BBD_DATABASE\Constraint\UsersTableConstraint.sql
:r C:\Users\bbdnet2897\Desktop\BBD_DATABASE\InsertToTable\InsertBBDFundData.sql
:r C:\Users\bbdnet2897\Desktop\BBD_DATABASE\InsertToTable\InsertContactDetailsData.sql
:r C:\Users\bbdnet2897\Desktop\BBD_DATABASE\InsertToTable\InsertDocumentData.sql
:r C:\Users\bbdnet2897\Desktop\BBD_DATABASE\InsertToTable\InsertProvinceData.sql
:r C:\Users\bbdnet2897\Desktop\BBD_DATABASE\InsertToTable\InsertRaceData.sql
:r C:\Users\bbdnet2897\Desktop\BBD_DATABASE\InsertToTable\InsertRoleData.sql
:r C:\Users\bbdnet2897\Desktop\BBD_DATABASE\InsertToTable\InsertStatus.sql
:r C:\Users\bbdnet2897\Desktop\BBD_DATABASE\InsertToTable\InsertStudentApplicationData.sql
:r C:\Users\bbdnet2897\Desktop\BBD_DATABASE\InsertToTable\InsertStudentInfomationData.sql
:r C:\Users\bbdnet2897\Desktop\BBD_DATABASE\InsertToTable\InsertUniversityData.sql
:r C:\Users\bbdnet2897\Desktop\BBD_DATABASE\InsertToTable\InsertUniversityFundApplicationData.sql
:r C:\Users\bbdnet2897\Desktop\BBD_DATABASE\InsertToTable\InsertUsersData.sql
